set(SOURCES_LIST
	conformation.C
	constraints.C
	conformationSet.C
	dockingAlgorithm.C
	dockResult.C
	flexDefinition.C
	flexibleMolecule.C
	gridAnalysis.C
	poseClustering.C
	receptor.C
	result.C
	sideChainOptimizer.C
	staticLigandFragment.C
	structurePreparer.C
)
