set(SOURCES_LIST
	AmiraMeshFile_test
	AntechamberFile_test
	BinaryFileAdaptor_test
	Bruker1DFile_test
	Bruker2DFile_test
	CCP4File_test
	DCDFile_test
	DockResultFile_test
	GenericMolFile_test
	HINFile_test
	HMOFile_test
	INIFile_test
	JCAMPFile_test
	KCFFile_test
	LineBasedFile_test
	MOLFile_test
	MOL2File_test
	NMRStarFile_test
	Parameters_test
	ParameterSection_test
	ResourceFile_test
	SDFile_test
	PDBInfo_test
	PDBFile_test
	SCWRLRotamerFile_test
	XYZFile_test
)
