### Directory name
SET(DIRECTORY source)

SET(TOOLS_SOURCES
	PDBDownload
)

SET(UTILITIES_SOURCES
	AddMissingAtoms
	AntitargetRescorer
	AutoModel
	BindingDBCleaner
	BondOrderAssigner
	CalculateBindingFreeEnergy
	CalculateEnergy
	CalculateSolvationFreeEnergy
	CombiLibGenerator
	ConstraintsFinder
	Converter
	CrystalGenerator
	DockPoseClustering
	DockResultMerger
	EvenSplit
	ExtractClustersFromWardTree
	ExtractProteinChains
	ExtractProteinSequence
	FeatureSelector
	FingerprintSimilarityClustering
	FingerprintSimilaritySearch
	GridBuilder
	IMGDock
	InputPartitioner
	InputReader
	InteractionConstraintDefiner
	Ligand3DGenerator
	LigandFileSplitter
	LigCheck
	ModelCreator
	MolCombine
	MolecularFileConverter
	MolFilter
	MolPredictor
	PartialChargesCopy
	PDBCutter
	PDBRMSDCalculator
	PeptideBuilder
	PocketDetector
	PoseIndices2PDB
	Predictor
	PropertyModifier
	PropertyPlotter
	ProteinCheck
	ProteinProtonator
	RemoveWater
	ResidueChecker
	RMSDCalculator
	ScoreAnalyzer
	SideChainGridBuilder
	SimilarityAnalyzer
	SimpleRescorer
	SLICK
	SpatialConstraintDefiner
	Split2ConnectedComponents
	TaGRes-train
	TaGRes
	Trajectory2RigidTransformation
	TrajectoryFile2PDBSplitter
	Validator
	WaterFinder
)

