set(SOURCES_LIST
	atomTypes.C
	charmmEEF1.C
	cosineTorsion.C
	forceFieldParameters.C
	lennardJones.C
	potential1210.C
	quadraticAngleBend.C
	quadraticBondStretch.C
	quadraticImproperTorsion.C
	residueTorsions.C
	templates.C
)	
